# Generated by Django 2.0.6 on 2018-07-02 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_auto_20180702_1116'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taskstatus',
            old_name='commment',
            new_name='comment',
        ),
    ]
