# Generated by Django 2.0.6 on 2018-06-22 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='name',
            field=models.CharField(db_index=True, default='name', max_length=128),
        ),
    ]
