# Generated by Django 2.0.6 on 2018-06-22 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0002_article_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='name',
            field=models.CharField(db_index=True, max_length=128, unique=True),
        ),
    ]
