# Generated by Django 2.0.6 on 2018-06-27 07:44

from django.db import migrations
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_auto_20180626_1747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='image_file',
            field=stdimage.models.StdImageField(blank=True, upload_to='stdimage'),
        ),
    ]
