# Generated by Django 2.0.6 on 2018-06-27 08:05

from django.db import migrations, models
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0004_auto_20180627_1259'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='image_thumbnail',
            field=imagekit.models.fields.ProcessedImageField(default='', upload_to='imagekit/2'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='photo',
            name='image_file',
            field=models.ImageField(upload_to='imagekit/1'),
        ),
    ]
